### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by mbkarle** [mbkarle/firstgames#100]
Make a legitimate interactive tutorial that details the buttons used, what certain stats mean, and how combat works.

**Comment by akarle** [comment]
Another option may be to start the game with a picture of the relevant keys and a description of what they do?

**Comment by mbkarle** [comment]
Optional tutorial is now in place at window load. Issue still open because I think it can be improved upon with combat simulation or other interactive guides.

**Comment by akarle** [comment]
Closed as basic tutorial done
