### ISSUE TITLE
NPC availability

### ISSUE THREAD

**Issue by mbkarle** [mbkarle/firstgames#107]
I'm torn on how to best balance finding NPCs. On one hand, I don't want the player to find all of them right away; on the other hand, I want players to get their benefits sooner rather than later as it is the means of the player character improving. Perhaps a floor/tier based solution rather than a random spawn?

**Comment by akarle** [comment]
Maybe the npcs "level up". Like when you buy stuff from them more stuff becomes available?

**Comment by akarle** [comment]
Or you perform quests to level them up?

**Comment by mbkarle** [comment]
On my current branch I've decided to make NPCs a guaranteed spawn somewhere on the first, third, fifth, and seventh floors, along with one random chance discovery. I've added all of them and their proposed purposes to the wiki if you're interested.

**Comment by akarle** [comment]
"Fixed to my satisfaction" @mbkarle  in commit e1e737f61887a0f2109f90c56ef5052b52c5016c
