### ISSUE TITLE
The Poor Merchant

### ISSUE THREAD

**Issue by akarle** [mbkarle/firstgames#125]
An interesting twist on a familiar character. 

### Background
Currently, the Merchant location (character?) will buy any amount of items from you. This makes it a good way to trade your loot for some cold hard cash (of which a portion is saved between rounds). 

**But**, not all merchants are born wealthy. For an interesting twist, what if each Merchant only has a certain amount they are willing to spend? Of course, if you buy from them, their budget increases by the amount you paid them (a trade perhaps). The poor Merchant adds an RNG element of maybe needing to ditch some of your weapons instead of constantly running back to the merchant on the floor and being able to sell them. 

### Implementation 
Implementation is easy. Use the new text mod to upon interaction announce the budget. 

The merchant as of the inventory refactor #119 will be have it’s own inventory. Buying items and selling items will basically be a paid transfer between your inventory and theirs.

And that’s where my inspiration came from. I thought “what if the hero’s money went somewhere?”. And such, the poor merchant was born.

**Comment by mbkarle** [comment]
I like this a lot

**Comment by akarle** [comment]
Cool!
