### ISSUE TITLE
Hardcode Item Values

### ISSUE THREAD

**Issue by akarle** [mbkarle/firstgames#127]
With the new Inventory update #119, we decided that we can manage the whole stingyness of a specific merchant randomly in the Merchant location (instead of randomly giving values). 

Base values for items **should** be given, as certain items just flat out are more valuable.

The RNG should come in with the spawn of the merchant and the use of the buyFrac/sellFrac parameters!

**Comment by akarle** [comment]
Duping #59 to this question

**Comment by mbkarle** [comment]
fixed by 148429122a6d26b6d894da0c014bf4708027d9cd
