### ISSUE TITLE
Enemies spawn on chests, locking you in

### ISSUE THREAD

**Issue by mbkarle** [mbkarle/firstgames#2]
If you trigger 5% chance of enemy spawn on landing on a chest you get locked in (can't enter combat, keep getting chest item)

Fixes:
1. no enemy spawns on chests
2. only enter chests once (chests expire after a single use)

**Comment by akarle** [comment]
I recommend 2, as its would solve the problem (you wouldn't get trapped by the chest popup) but its probably a better game mechanic..
