### ISSUE TITLE
Combat should only run when you enter combat

### ISSUE THREAD

**Issue by akarle** [mbkarle/firstgames#31]
We talked about this earlier, but it would potentially solve our #18 problem (see comments) if we only ran `combat` and `combat_helper` when we actually went into combat. 

Like we have a `fightChance` which only causes the `combat-module` to display, but really `combat()` should only be called if the fightChance is true. It shouldn't be running in the background always, and I think this may be the source of some of our bigger problems that underly our code.

**Comment by mbkarle** [comment]
While I would argue that the current system is running perfectly fine (#18 has been fixed; no apparent underlying issues), I concede that this enhancement would make a lot of things easier and reduce redundancies in the future. If it can conceivably be done without destroying the code, I think it would be a worthwhile (probably not _crucial_) endeavor.

**Comment by akarle** [comment]
workin on it.... #41 is a start
