### ISSUE TITLE
Rooms

### ISSUE THREAD

**Issue by mbkarle** [mbkarle/firstgames#35]
Floor 0 especially could benefit from the introduction of rooms. The current area is a pretty small space that might seem crowded once more locations are added. Rooms on floor 0 could be essentially categorized by content; i.e. one room might contain various tutorial dialogues, while another would contain various merchants and vendors.

**Comment by akarle** [comment]
I agree--maybe even introduce a door location to interact with? Like a square that isn't filled

**Comment by akarle** [comment]
Boom #41
