### ISSUE TITLE
Clean up the print function

### ISSUE THREAD

**Issue by akarle** [mbkarle/firstgames#4]
I feel like its pretty sloppy to have it take in 4 different types for param @message... It makes it hard to read code calling print because of its inconsistent behavior.

Maybe look into having prints for objects as functions of the objects?

**Comment by mbkarle** [comment]
content-branch makes lastMessage much more efficient by introducing second dimension to hold messageTypes in messageArray

param `@message` still has 4 different types though

**Comment by akarle** [comment]
This is no longer causing any problems... It is what it is.
