### ISSUE TITLE
Shield is broken. again.

### ISSUE THREAD

**Issue by akarle** [mbkarle/firstgames#58]
Rip. Likely the move to combat only running when you're in combat.

**Comment by mbkarle** [comment]
I have not seen any issues with shield. Can you recreate the bug @akarle ? Or provide more context surrounding the bug if possible so that I can attempt to recreate it.

**Comment by akarle** [comment]
So it was on the first enemy, he had already taken damage, he pressed the shield button (maybe a couple times) and the slider loaded, and then he took damage. Or so it seemed. Maybe he clicked away?

**Comment by akarle** [comment]
Yeah idk, I can't reproduce it, so maybe I just thought I saw it / he clicked away? #61

**Comment by akarle** [comment]
Closing for now, will reopen if it crops up again
