### ISSUE TITLE
Item value mapping

### ISSUE THREAD

**Issue by mbkarle** [mbkarle/firstgames#59]
Prices are currently assigned arbitrarily. While this could be excused in plot as merchants subjectively pricing things based on what they want and are willing to let go, but game logic states that a more powerful item should be more expensive than a weaker one.

**Comment by akarle** [comment]
Maybe make it a property of all items? Retail value = X, sell value = .7*retail value

**Comment by akarle** [comment]
Still active @mbkarle bump!
