### ISSUE TITLE
Consumables and Resources

### ISSUE THREAD

**Issue by mbkarle** [mbkarle/firstgames#69]
Right now every item is equipment that must be equipped to serve any functionality. Ultimately you should be able to find consumables (such as potions or one time use weapons) or resources that can stack in the inventory and be used outside of equipping

**Comment by akarle** [comment]
Torch and Gold are our first ventures into this area. 

I'm thinking potions be an item like others but instead of "Equip" it gets a "use" button. Some should be instantaneous (health) others duration (attack speed).

**Comment by akarle** [comment]
Consumables are here through the NPC update
